<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>estimate_icon-removebg-preview.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="estimate_icon-removebg-preview.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.3" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.1.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4181-prerelease" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="QuestPDF" Version="2026.7.2" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="estimate_icon-removebg-preview.ico" />
  </ItemGroup>

</Project>
